USE [master]
GO

/****** Object:  Database [EzraDB]    Script Date: 12/20/2021 9:46:30 PM ******/
CREATE DATABASE [EzraDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EzraDB', FILENAME = N'G:\SQL\MSSQL15.MSSQLSERVER\MSSQL\DATA\EzraDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EzraDB_log', FILENAME = N'G:\SQL\MSSQL15.MSSQLSERVER\MSSQL\DATA\EzraDB_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EzraDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EzraDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EzraDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EzraDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EzraDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EzraDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [EzraDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EzraDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EzraDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EzraDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EzraDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EzraDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EzraDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EzraDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EzraDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EzraDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [EzraDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EzraDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EzraDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EzraDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EzraDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EzraDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [EzraDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EzraDB] SET RECOVERY FULL 
GO

ALTER DATABASE [EzraDB] SET  MULTI_USER 
GO

ALTER DATABASE [EzraDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EzraDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EzraDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EzraDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EzraDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EzraDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EzraDB] SET  READ_WRITE 
GO

